"""
Auto-generated ctypes wrapper for the Entropic C API.

Generated by scripts/generate_wrapper.py from entropic.h.
DO NOT EDIT — changes will be overwritten on next build.

@brief Ctypes bindings for librentropic C API.
@version 1
"""

from __future__ import annotations

import ctypes
import ctypes.util
import enum
import json
import os
import threading
from collections.abc import Callable
from dataclasses import dataclass, field
from typing import Any

_LIB_NAME = "librentropic.so"


# ── Enums ────────────────────────────────────────────


class Error(enum.IntEnum):
    """Mirror of C entropic_error_t."""

    OK = 0  # Success
    INVALID_ARGUMENT = 1  # NULL pointer, empty string, out-of-range value
    INVALID_CONFIG = 2  # Config validation failed (missing fields, bad values)
    INVALID_STATE = 3  # Operation not valid in current state (e.g., generate before activate)
    MODEL_NOT_FOUND = 4  # Model file does not exist at resolved path
    LOAD_FAILED = 5  # Model load failed (corrupt file, OOM, unsupported format)
    GENERATE_FAILED = 6  # Generation failed (context overflow, model error)
    TOOL_NOT_FOUND = 7  # Requested tool not registered
    PERMISSION_DENIED = 8  # Tool call blocked by permission manager
    PLUGIN_VERSION_MISMATCH = 9  # Plugin API version != engine expected version
    PLUGIN_LOAD_FAILED = 10  # dlopen/dlsym failed on plugin .so
    TIMEOUT = 11  # Operation exceeded time limit
    CANCELLED = 12  # Operation cancelled via cancel token
    OUT_OF_MEMORY = 13  # Allocation failed (system RAM or VRAM)
    IO = 14  # File/network I/O error
    INTERNAL = 15  # Unexpected internal error (bug)
    SERVER_ALREADY_EXISTS = 16  # MCP server name already registered (v1.8.7)
    SERVER_NOT_FOUND = 17  # MCP server name not found (v1.8.7)
    CONNECTION_FAILED = 18  # Transport connection failed (v1.8.7)
    INVALID_HANDLE = 19  # NULL or destroyed handle (v1.8.9)
    TOOL_EXECUTION_FAILED = 20  # Tool call returned error (v1.8.9)
    STORAGE_FAILED = 21  # Storage operation failed (v1.8.9)
    IDENTITY_NOT_FOUND = 22  # Identity name not in config (v1.8.9)
    ALREADY_RUNNING = 23  # entropic_run already in progress on handle (v1.8.9)
    NOT_RUNNING = 24  # Interrupt called but nothing running (v1.8.9)
    NOT_IMPLEMENTED = 25  # Feature stub, not yet available (v1.8.9)
    INTERRUPTED = 26  # Operation interrupted via entropic_interrupt (v1.8.9)
    ADAPTER_NOT_FOUND = 27  # Adapter name not recognized (v1.9.2)
    ADAPTER_LOAD_FAILED = 28  # LoRA file invalid or incompatible with base model (v1.9.2)
    ADAPTER_SWAP_FAILED = 29  # Swap failed (e.g., base model not ACTIVE) (v1.9.2)
    ADAPTER_CANCELLED = 30  # ON_ADAPTER_SWAP hook cancelled the operation (v1.9.2)
    GRAMMAR_NOT_FOUND = 31  # Grammar key not in registry (v1.9.3)
    GRAMMAR_INVALID = 32  # GBNF parse failed (v1.9.3)
    MCP_KEY_DENIED = 33  # Tool call denied by MCP key set (v1.9.4)
    LIMIT_REACHED = 34  # Resource limit exceeded (e.g., max_identities) (v1.9.6)
    ALREADY_EXISTS = 35  # Named resource already exists (v1.9.6)
    IN_USE = 36  # Resource is currently active and cannot be removed (v1.9.6)
    PROFILE_NOT_FOUND = 37  # Profile name not in registry (v1.9.7)
    TIME_LIMIT_EXCEEDED = 38  # Generation terminated by time cap (v1.9.7)
    VALIDATION_FAILED = 39  # Critique generation failed — infrastructure, not content (v1.9.8)
    COMPACTION_FAILED = (
        40  # Custom compactor returned non-zero and default fallback also failed (v1.9.9)
    )
    MODEL_NOT_ACTIVE = 41  # Model exists but not in ACTIVE state (v1.9.10)
    EVAL_CONTEXT_FULL = 42  # Sequence exceeds model context window (v1.9.10)
    EVAL_FAILED = 43  # Evaluation failed (llama_decode error) (v1.9.10)
    IMAGE_LOAD_FAILED = 44  # Image file could not be read or decoded (v1.9.11)
    IMAGE_TOO_LARGE = 45  # Image exceeds max_file_size (v1.9.11)
    MMPROJ_LOAD_FAILED = 46  # mmproj GGUF failed to load (v1.9.11)
    UNSUPPORTED_URL = 47  # Remote URL not supported — local file or data URI only (v1.9.11)
    NOT_SUPPORTED = 48  # Capability not supported by this backend (v1.9.13)
    STATE_INCOMPATIBLE = 49  # State buffer incompatible with current model (v1.9.13)


class HookPoint(enum.IntEnum):
    """Mirror of C entropic_hook_point_t."""

    PRE_GENERATE = 0  # 0: Before inference generate call
    POST_GENERATE = 1  # 1: After inference generate returns
    ON_STREAM_TOKEN = 2  # 2: Each streaming token emitted
    PRE_TOOL_CALL = 3  # 3: Before tool execution
    POST_TOOL_CALL = 4  # 4: After tool execution returns
    ON_LOOP_ITERATION = 5  # 5: Each agentic loop iteration
    ON_STATE_CHANGE = 6  # 6: Engine state machine transition
    ON_ERROR = 7  # 7: Async error occurred
    ON_DELEGATE = 8  # 8: Delegation to child tier started
    ON_DELEGATE_COMPLETE = 9  # 9: Child delegation completed
    ON_CONTEXT_ASSEMBLE = 10  # 10: Context window assembled
    ON_PRE_COMPACT = 11  # 11: Before context compaction
    ON_POST_COMPACT = 12  # 12: After context compaction
    ON_MODEL_LOAD = 13  # 13: Model loaded into backend
    ON_MODEL_UNLOAD = 14  # 14: Model unloaded from backend
    ON_PERMISSION_CHECK = 15  # 15: Permission check evaluated
    ON_ADAPTER_SWAP = 16  # 16: Adapter/LoRA swap requested
    ON_VRAM_PRESSURE = 17  # 17: VRAM pressure detected
    ON_DIRECTIVE = 18  # 18: Before processing a directive
    ON_CUSTOM_DIRECTIVE = 19  # 19: Unrecognized directive type
    ON_LOOP_START = 20  # 20: Agentic loop entry
    ON_LOOP_END = 21  # 21: Agentic loop exit
    COUNT_ = 22  # Sentinel — not a valid hook point


# ── Callback Types ───────────────────────────────────

entropic_error_callback_t = ctypes.CFUNCTYPE(None, ctypes.c_int, ctypes.c_char_p, ctypes.c_void_p)
entropic_hook_callback_t = ctypes.CFUNCTYPE(
    ctypes.c_int, ctypes.c_int, ctypes.c_char_p, ctypes.POINTER(ctypes.c_void_p), ctypes.c_void_p
)


## ── Library Discovery ────────────────────────────────────


## @brief Find and load the entropic shared library.
## @utility
## @return Loaded ctypes.CDLL handle.
## @version 1
def _find_library() -> ctypes.CDLL:
    """Locate and load librentropic.so.

    Search order:
    1. ENTROPIC_LIB_PATH environment variable
    2. Adjacent to this module (python/entropic/lib/)
    3. System library paths (ldconfig)
    4. Build directory

    @brief Find and load the entropic shared library.
    @version 1
    """
    search_paths = [
        os.environ.get("ENTROPIC_LIB_PATH"),
        os.path.join(os.path.dirname(__file__), "lib", "librentropic.so"),
    ]

    for path in search_paths:
        if path and os.path.isfile(path):
            return ctypes.CDLL(path)

    # Try system library paths
    system_lib = ctypes.util.find_library("rentropic")
    if system_lib:
        return ctypes.CDLL(system_lib)

    raise ImportError(
        "librentropic.so not found. Set ENTROPIC_LIB_PATH or install entropic-engine. "
        "Searched: ENTROPIC_LIB_PATH env var, module lib/ dir, system paths."
    )


# Load library at import time — fail fast if not found
_lib: ctypes.CDLL | None = None


## @brief Lazy library loader — defers ImportError until first use.
## @utility
## @return Loaded ctypes.CDLL handle.
## @version 1
def _get_lib() -> ctypes.CDLL:
    """Get the loaded library, loading lazily on first access.

    @brief Lazy library loader — defers ImportError until first use.
    @version 1
    """
    global _lib  # noqa: PLW0603
    if _lib is None:
        _lib = _find_library()
    return _lib


## ── Function Bindings ────────────────────────────────


## @brief Set ctypes type signatures for all exported functions.
## @utility
## @version 1
def _setup_bindings(lib: ctypes.CDLL) -> None:  # noqa: CFQ001  # auto-generated
    """Configure argtypes and restype for all C API functions.

    @brief Set ctypes type signatures for all exported functions.
    @version 1
    """
    lib.entropic_create.restype = ctypes.c_int
    lib.entropic_create.argtypes = [ctypes.POINTER(ctypes.c_void_p)]

    lib.entropic_configure.restype = ctypes.c_int
    lib.entropic_configure.argtypes = [ctypes.c_void_p, ctypes.c_char_p]

    lib.entropic_configure_from_file.restype = ctypes.c_int
    lib.entropic_configure_from_file.argtypes = [ctypes.c_void_p, ctypes.c_char_p]

    lib.entropic_configure_dir.restype = ctypes.c_int
    lib.entropic_configure_dir.argtypes = [ctypes.c_void_p, ctypes.c_char_p]

    lib.entropic_destroy.restype = None
    lib.entropic_destroy.argtypes = [ctypes.c_void_p]

    lib.entropic_version.restype = ctypes.c_char_p
    lib.entropic_version.argtypes = []

    lib.entropic_api_version.restype = ctypes.c_int
    lib.entropic_api_version.argtypes = []

    lib.entropic_alloc.restype = ctypes.c_void_p
    lib.entropic_alloc.argtypes = [ctypes.c_size_t]

    lib.entropic_free.restype = None
    lib.entropic_free.argtypes = [ctypes.c_void_p]

    lib.entropic_run.restype = ctypes.c_int
    lib.entropic_run.argtypes = [ctypes.c_void_p, ctypes.c_char_p, ctypes.POINTER(ctypes.c_void_p)]

    lib.entropic_run_streaming.restype = ctypes.c_int
    lib.entropic_run_streaming.argtypes = [
        ctypes.c_void_p,
        ctypes.c_char_p,
        ctypes.c_void_p,
        ctypes.c_void_p,
        ctypes.POINTER(ctypes.c_int),
    ]

    lib.entropic_interrupt.restype = ctypes.c_int
    lib.entropic_interrupt.argtypes = [ctypes.c_void_p]

    lib.entropic_context_clear.restype = ctypes.c_int
    lib.entropic_context_clear.argtypes = [ctypes.c_void_p]

    lib.entropic_context_get.restype = ctypes.c_int
    lib.entropic_context_get.argtypes = [ctypes.c_void_p, ctypes.POINTER(ctypes.c_void_p)]

    lib.entropic_context_count.restype = ctypes.c_int
    lib.entropic_context_count.argtypes = [ctypes.c_void_p, ctypes.c_void_p]

    lib.entropic_register_mcp_server.restype = ctypes.c_int
    lib.entropic_register_mcp_server.argtypes = [ctypes.c_void_p, ctypes.c_char_p, ctypes.c_char_p]

    lib.entropic_deregister_mcp_server.restype = ctypes.c_int
    lib.entropic_deregister_mcp_server.argtypes = [ctypes.c_void_p, ctypes.c_char_p]

    lib.entropic_list_mcp_servers.restype = ctypes.c_char_p
    lib.entropic_list_mcp_servers.argtypes = [ctypes.c_void_p]

    lib.entropic_storage_open.restype = ctypes.c_int
    lib.entropic_storage_open.argtypes = [ctypes.c_void_p, ctypes.c_char_p]

    lib.entropic_storage_close.restype = ctypes.c_int
    lib.entropic_storage_close.argtypes = [ctypes.c_void_p]

    lib.entropic_load_identity.restype = ctypes.c_int
    lib.entropic_load_identity.argtypes = [ctypes.c_void_p, ctypes.c_char_p]

    lib.entropic_get_identity.restype = ctypes.c_int
    lib.entropic_get_identity.argtypes = [ctypes.c_void_p, ctypes.POINTER(ctypes.c_void_p)]

    lib.entropic_register_hook.restype = ctypes.c_int
    lib.entropic_register_hook.argtypes = [
        ctypes.c_void_p,
        ctypes.c_int,
        entropic_hook_callback_t,
        ctypes.c_void_p,
        ctypes.c_int,
    ]

    lib.entropic_deregister_hook.restype = ctypes.c_int
    lib.entropic_deregister_hook.argtypes = [
        ctypes.c_void_p,
        ctypes.c_int,
        entropic_hook_callback_t,
        ctypes.c_void_p,
    ]

    lib.entropic_adapter_load.restype = ctypes.c_int
    lib.entropic_adapter_load.argtypes = [
        ctypes.c_void_p,
        ctypes.c_char_p,
        ctypes.c_char_p,
        ctypes.c_char_p,
        ctypes.c_void_p,
    ]

    lib.entropic_adapter_unload.restype = ctypes.c_int
    lib.entropic_adapter_unload.argtypes = [ctypes.c_void_p, ctypes.c_char_p]

    lib.entropic_adapter_swap.restype = ctypes.c_int
    lib.entropic_adapter_swap.argtypes = [ctypes.c_void_p, ctypes.c_char_p]

    lib.entropic_adapter_state.restype = ctypes.c_int
    lib.entropic_adapter_state.argtypes = [ctypes.c_void_p, ctypes.c_char_p]

    lib.entropic_adapter_info.restype = ctypes.c_char_p
    lib.entropic_adapter_info.argtypes = [ctypes.c_void_p, ctypes.c_char_p]

    lib.entropic_adapter_list.restype = ctypes.c_char_p
    lib.entropic_adapter_list.argtypes = [ctypes.c_void_p]

    lib.entropic_grammar_register.restype = ctypes.c_int
    lib.entropic_grammar_register.argtypes = [ctypes.c_void_p, ctypes.c_char_p, ctypes.c_char_p]

    lib.entropic_grammar_register_file.restype = ctypes.c_int
    lib.entropic_grammar_register_file.argtypes = [
        ctypes.c_void_p,
        ctypes.c_char_p,
        ctypes.c_char_p,
    ]

    lib.entropic_grammar_deregister.restype = ctypes.c_int
    lib.entropic_grammar_deregister.argtypes = [ctypes.c_void_p, ctypes.c_char_p]

    lib.entropic_grammar_get.restype = ctypes.c_char_p
    lib.entropic_grammar_get.argtypes = [ctypes.c_void_p, ctypes.c_char_p]

    lib.entropic_grammar_validate.restype = ctypes.c_char_p
    lib.entropic_grammar_validate.argtypes = [ctypes.c_char_p]

    lib.entropic_grammar_list.restype = ctypes.c_char_p
    lib.entropic_grammar_list.argtypes = [ctypes.c_void_p]

    lib.entropic_profile_register.restype = ctypes.c_int
    lib.entropic_profile_register.argtypes = [ctypes.c_void_p, ctypes.c_char_p]

    lib.entropic_profile_deregister.restype = ctypes.c_int
    lib.entropic_profile_deregister.argtypes = [ctypes.c_void_p, ctypes.c_char_p]

    lib.entropic_profile_get.restype = ctypes.c_char_p
    lib.entropic_profile_get.argtypes = [ctypes.c_void_p, ctypes.c_char_p]

    lib.entropic_profile_list.restype = ctypes.c_char_p
    lib.entropic_profile_list.argtypes = [ctypes.c_void_p]

    lib.entropic_throughput_tok_per_sec.restype = ctypes.c_void_p
    lib.entropic_throughput_tok_per_sec.argtypes = [ctypes.c_void_p, ctypes.c_char_p]

    lib.entropic_throughput_reset.restype = None
    lib.entropic_throughput_reset.argtypes = [ctypes.c_void_p, ctypes.c_char_p]

    lib.entropic_grant_mcp_key.restype = ctypes.c_int
    lib.entropic_grant_mcp_key.argtypes = [
        ctypes.c_void_p,
        ctypes.c_char_p,
        ctypes.c_char_p,
        ctypes.c_void_p,
    ]

    lib.entropic_revoke_mcp_key.restype = ctypes.c_int
    lib.entropic_revoke_mcp_key.argtypes = [ctypes.c_void_p, ctypes.c_char_p, ctypes.c_char_p]

    lib.entropic_check_mcp_key.restype = ctypes.c_int
    lib.entropic_check_mcp_key.argtypes = [
        ctypes.c_void_p,
        ctypes.c_char_p,
        ctypes.c_char_p,
        ctypes.c_void_p,
    ]

    lib.entropic_list_mcp_keys.restype = ctypes.c_char_p
    lib.entropic_list_mcp_keys.argtypes = [ctypes.c_void_p, ctypes.c_char_p]

    lib.entropic_grant_mcp_key_from.restype = ctypes.c_int
    lib.entropic_grant_mcp_key_from.argtypes = [
        ctypes.c_void_p,
        ctypes.c_char_p,
        ctypes.c_char_p,
        ctypes.c_char_p,
        ctypes.c_void_p,
    ]

    lib.entropic_serialize_mcp_keys.restype = ctypes.c_char_p
    lib.entropic_serialize_mcp_keys.argtypes = [ctypes.c_void_p]

    lib.entropic_deserialize_mcp_keys.restype = ctypes.c_int
    lib.entropic_deserialize_mcp_keys.argtypes = [ctypes.c_void_p, ctypes.c_char_p]

    lib.entropic_audit_flush.restype = ctypes.c_int
    lib.entropic_audit_flush.argtypes = [ctypes.c_void_p]

    lib.entropic_audit_count.restype = ctypes.c_int
    lib.entropic_audit_count.argtypes = [ctypes.c_void_p, ctypes.c_void_p]

    lib.entropic_audit_read.restype = ctypes.c_int
    lib.entropic_audit_read.argtypes = [
        ctypes.c_void_p,
        ctypes.c_char_p,
        ctypes.c_char_p,
        ctypes.POINTER(ctypes.c_void_p),
    ]

    lib.entropic_create_identity.restype = ctypes.c_int
    lib.entropic_create_identity.argtypes = [ctypes.c_void_p, ctypes.c_char_p]

    lib.entropic_update_identity.restype = ctypes.c_int
    lib.entropic_update_identity.argtypes = [ctypes.c_void_p, ctypes.c_char_p, ctypes.c_char_p]

    lib.entropic_destroy_identity.restype = ctypes.c_int
    lib.entropic_destroy_identity.argtypes = [ctypes.c_void_p, ctypes.c_char_p]

    lib.entropic_get_identity_config.restype = ctypes.c_char_p
    lib.entropic_get_identity_config.argtypes = [ctypes.c_void_p, ctypes.c_char_p]

    lib.entropic_list_identities.restype = ctypes.c_char_p
    lib.entropic_list_identities.argtypes = [ctypes.c_void_p]

    lib.entropic_identity_count.restype = ctypes.c_int
    lib.entropic_identity_count.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p]

    lib.entropic_compact.restype = ctypes.c_int
    lib.entropic_compact.argtypes = [
        ctypes.c_void_p,
        ctypes.c_char_p,
        ctypes.POINTER(ctypes.c_void_p),
    ]

    lib.entropic_register_compactor.restype = ctypes.c_int
    lib.entropic_register_compactor.argtypes = [
        ctypes.c_void_p,
        ctypes.c_char_p,
        ctypes.c_void_p,
        ctypes.c_void_p,
    ]

    lib.entropic_deregister_compactor.restype = ctypes.c_int
    lib.entropic_deregister_compactor.argtypes = [ctypes.c_void_p, ctypes.c_char_p]

    lib.entropic_get_default_compactor.restype = ctypes.c_int
    lib.entropic_get_default_compactor.argtypes = [
        ctypes.c_void_p,
        ctypes.c_void_p,
        ctypes.POINTER(ctypes.c_void_p),
    ]

    lib.entropic_get_logprobs.restype = ctypes.c_int
    lib.entropic_get_logprobs.argtypes = [
        ctypes.c_void_p,
        ctypes.c_char_p,
        ctypes.c_void_p,
        ctypes.c_int,
        ctypes.c_void_p,
    ]

    lib.entropic_compute_perplexity.restype = ctypes.c_int
    lib.entropic_compute_perplexity.argtypes = [
        ctypes.c_void_p,
        ctypes.c_char_p,
        ctypes.c_void_p,
        ctypes.c_int,
        ctypes.c_void_p,
    ]

    lib.entropic_free_logprob_result.restype = None
    lib.entropic_free_logprob_result.argtypes = [ctypes.c_void_p]

    lib.entropic_validation_set_enabled.restype = ctypes.c_int
    lib.entropic_validation_set_enabled.argtypes = [ctypes.c_void_p, ctypes.c_void_p]

    lib.entropic_validation_set_identity.restype = ctypes.c_int
    lib.entropic_validation_set_identity.argtypes = [
        ctypes.c_void_p,
        ctypes.c_char_p,
        ctypes.c_void_p,
    ]

    lib.entropic_validation_last_result.restype = ctypes.c_char_p
    lib.entropic_validation_last_result.argtypes = [ctypes.c_void_p]

    lib.entropic_model_has_vision.restype = ctypes.c_int
    lib.entropic_model_has_vision.argtypes = [ctypes.c_void_p, ctypes.c_char_p]

    lib.entropic_get_diagnostic_prompt.restype = ctypes.c_int
    lib.entropic_get_diagnostic_prompt.argtypes = [ctypes.c_void_p, ctypes.POINTER(ctypes.c_void_p)]

    lib.entropic_last_error.restype = ctypes.c_char_p
    lib.entropic_last_error.argtypes = [ctypes.c_void_p]

    lib.entropic_error_name.restype = ctypes.c_char_p
    lib.entropic_error_name.argtypes = [ctypes.c_int]

    lib.entropic_set_error_callback.restype = ctypes.c_int
    lib.entropic_set_error_callback.argtypes = [
        ctypes.c_void_p,
        entropic_error_callback_t,
        ctypes.c_void_p,
    ]


# ── Error Handling ───────────────────────────────────────


class EntropicError(Exception):
    """Exception raised for entropic C engine errors.

    @brief Python exception wrapping entropic_error_t codes.
    @version 1
    """

    ## @brief Initialize with error code and message.
    ## @utility
    ## @version 1
    def __init__(self, code: int, message: str):
        self.code = code
        self.message = message
        try:
            self.error_type = Error(code)
        except ValueError:
            self.error_type = None
        super().__init__(f"entropic error {code}: {message}")


## @brief Convert non-OK error codes to EntropicError exceptions.
## @utility
## @version 1
def _check_error(handle: ctypes.c_void_p, error_code: int) -> None:
    """Check an entropic_error_t return and raise on failure.

    @brief Convert non-OK error codes to EntropicError exceptions.
    @version 1
    """
    if error_code == 0:
        return
    lib = _get_lib()
    msg_ptr = lib.entropic_last_error(handle)
    msg = msg_ptr.decode() if msg_ptr else "unknown error"
    raise EntropicError(error_code, msg)


# ── Memory Management ────────────────────────────────────


class _OwnedString:
    """RAII wrapper for strings allocated by the C engine.

    Ensures entropic_free() is called when the string is no longer needed.

    @brief Auto-freeing wrapper for engine-allocated char* strings.
    @version 1
    """

    ## @brief Store pointer to engine-allocated string.
    ## @utility
    ## @version 1
    def __init__(self, ptr: ctypes.c_void_p):
        self._ptr = ptr

    ## @brief Decode and return the C string.
    ## @utility
    ## @return Decoded string or empty string if null.
    ## @version 1
    def __str__(self) -> str:
        if self._ptr:
            return ctypes.cast(self._ptr, ctypes.c_char_p).value.decode()
        return ""

    ## @brief Free the engine-allocated string.
    ## @utility
    ## @version 1
    def __del__(self) -> None:
        if self._ptr:
            lib = _get_lib()
            lib.entropic_free(self._ptr)
            self._ptr = None


# ── Engine Class ─────────────────────────────────────────


# ctypes callback type for streaming tokens
_StreamCallbackType = ctypes.CFUNCTYPE(
    None,
    ctypes.c_char_p,  # token
    ctypes.c_size_t,  # len
    ctypes.c_void_p,  # user_data
)


class EntropicEngine:
    """High-level wrapper around the entropic C engine.

    Manages the lifecycle of an entropic_handle_t. Use as a context
    manager or call destroy() explicitly.

    @brief Python wrapper for entropic engine handle lifecycle.
    @version 1
    """

    ## @brief Create engine handle and apply configuration.
    ## @utility
    ## @version 1
    def __init__(
        self,
        config_path: str | None = None,
        config_json: str | None = None,
    ):
        """Create and optionally configure an engine instance.

        @brief Create engine handle and apply configuration.
        @version 1
        """
        lib = _get_lib()
        _setup_bindings(lib)

        self._handle = ctypes.c_void_p()
        _check_error(None, lib.entropic_create(ctypes.byref(self._handle)))

        if not self._handle:
            raise RuntimeError("entropic_create returned NULL handle")

        try:
            if config_path:
                _check_error(
                    self._handle,
                    lib.entropic_configure_from_file(
                        self._handle,
                        config_path.encode(),
                    ),
                )
            elif config_json:
                _check_error(
                    self._handle,
                    lib.entropic_configure(
                        self._handle,
                        config_json.encode(),
                    ),
                )
        except Exception:
            lib.entropic_destroy(self._handle)
            self._handle = None
            raise

        self._lib = lib

    ## @brief Execute entropic_run and return parsed result.
    ## @utility
    ## @return GenerationResult from the engine.
    ## @version 1
    def run(self, prompt: str) -> GenerationResult:
        """Run the agentic loop synchronously.

        @brief Execute entropic_run and return parsed result.
        @version 1
        """
        result_ptr = ctypes.c_char_p()
        _check_error(
            self._handle,
            self._lib.entropic_run(
                self._handle,
                prompt.encode(),
                ctypes.byref(result_ptr),
            ),
        )
        try:
            result_json = result_ptr.value.decode() if result_ptr.value else "{}"
            return GenerationResult.from_json(result_json)
        finally:
            if result_ptr.value:
                self._lib.entropic_free(result_ptr)

    ## @brief Execute entropic_run_streaming with Python callback.
    ## @utility
    ## @version 1
    def run_streaming(
        self,
        prompt: str,
        on_token: Callable[[str], None],
        cancel: threading.Event | None = None,
    ) -> None:
        """Run the agentic loop with streaming token callback.

        @brief Execute entropic_run_streaming with Python callback.
        @version 1
        """
        cancel_flag = ctypes.c_int(0)

        ## @brief Background thread to bridge Event to C cancel_flag.
        ## @callback
        ## @version 1
        def _cancel_monitor() -> None:
            """Monitor cancel event and set flag.

            @brief Background thread to bridge Event to C cancel_flag.
            @version 1
            """
            if cancel:
                cancel.wait()
                cancel_flag.value = 1

        if cancel:
            monitor = threading.Thread(target=_cancel_monitor, daemon=True)
            monitor.start()

        ## @brief Bridge ctypes callback to user-provided on_token.
        ## @callback
        ## @version 1
        @_StreamCallbackType
        def _on_token_cb(
            token: bytes,
            length: int,
            user_data: ctypes.c_void_p,  # noqa: ARG001
        ) -> None:
            """Forward C token callback to Python callable.

            @brief Bridge ctypes callback to user-provided on_token.
            @version 1
            """
            if token:
                on_token(token[:length].decode())

        _check_error(
            self._handle,
            self._lib.entropic_run_streaming(
                self._handle,
                prompt.encode(),
                _on_token_cb,
                None,
                ctypes.byref(cancel_flag),
            ),
        )

    ## @brief Signal the engine to abort current run.
    ## @utility
    ## @version 1
    def interrupt(self) -> None:
        """Interrupt a running generation.

        @brief Signal the engine to abort current run.
        @version 1
        """
        _check_error(
            self._handle,
            self._lib.entropic_interrupt(self._handle),
        )

    ## @brief Set active identity for subsequent runs.
    ## @utility
    ## @version 1
    def load_identity(self, name: str) -> None:
        """Load an identity by name.

        @brief Set active identity for subsequent runs.
        @version 1
        """
        _check_error(
            self._handle,
            self._lib.entropic_load_identity(
                self._handle,
                name.encode(),
            ),
        )

    ## @brief Retrieve active identity JSON from C engine.
    ## @utility
    ## @return Identity as a dict.
    ## @version 1
    def get_identity(self) -> dict[str, Any]:
        """Get the current active identity as a dict.

        @brief Retrieve active identity JSON from C engine.
        @version 1
        """
        result_ptr = ctypes.c_char_p()
        _check_error(
            self._handle,
            self._lib.entropic_get_identity(
                self._handle,
                ctypes.byref(result_ptr),
            ),
        )
        try:
            return json.loads(result_ptr.value.decode() if result_ptr.value else "{}")
        finally:
            if result_ptr.value:
                self._lib.entropic_free(result_ptr)

    ## @brief Configure engine from JSON after creation.
    ## @utility
    ## @version 1
    def configure(self, config_json: str) -> None:
        """Apply configuration from a JSON string.

        @brief Configure engine from JSON after creation.
        @version 1
        """
        _check_error(
            self._handle,
            self._lib.entropic_configure(
                self._handle,
                config_json.encode(),
            ),
        )

    ## @brief Configure engine from file after creation.
    ## @utility
    ## @version 1
    def configure_from_file(self, config_path: str) -> None:
        """Apply configuration from a YAML/JSON file.

        @brief Configure engine from file after creation.
        @version 1
        """
        _check_error(
            self._handle,
            self._lib.entropic_configure_from_file(
                self._handle,
                config_path.encode(),
            ),
        )

    ## @brief Layered config resolution from project directory.
    ## @utility
    ## @version 1
    def configure_dir(self, project_dir: str) -> None:
        """Configure using layered resolution from a project directory.

        Loads: bundled default -> ~/.entropic/config.yaml ->
        {project_dir}/config.local.yaml -> env overrides.

        @brief Layered config resolution from project directory.
        @version 1
        """
        _check_error(
            self._handle,
            self._lib.entropic_configure_dir(
                self._handle,
                project_dir.encode(),
            ),
        )

    ## @brief Reset conversation to empty.
    ## @utility
    ## @version 1
    def context_clear(self) -> None:
        """Clear conversation history, starting a new session.

        @brief Reset conversation to empty.
        @version 1
        """
        _check_error(
            self._handle,
            self._lib.entropic_context_clear(self._handle),
        )

    ## @brief Return conversation as list of message dicts.
    ## @utility
    ## @return List of {role, content} dicts.
    ## @version 1
    def context_get(self) -> list[dict[str, Any]]:
        """Get the current conversation history.

        @brief Return conversation as list of {role, content} dicts.
        @version 1
        """
        result_ptr = ctypes.c_void_p()
        _check_error(
            self._handle,
            self._lib.entropic_context_get(
                self._handle,
                ctypes.byref(result_ptr),
            ),
        )
        try:
            raw = ctypes.cast(result_ptr, ctypes.c_char_p).value
            return json.loads(raw.decode() if raw else "[]")
        finally:
            if result_ptr.value:
                self._lib.entropic_free(result_ptr)

    ## @brief Return message count.
    ## @utility
    ## @return Number of messages in conversation.
    ## @version 1
    def context_count(self) -> int:
        """Get the number of messages in the conversation.

        @brief Return message count.
        @version 1
        """
        count = ctypes.c_size_t(0)
        _check_error(
            self._handle,
            self._lib.entropic_context_count(
                self._handle,
                ctypes.byref(count),
            ),
        )
        return count.value

    ## @brief Initialize persistent storage for conversations.
    ## @utility
    ## @version 1
    def storage_open(self, db_path: str) -> None:
        """Open SQLite storage backend.

        @brief Initialize persistent storage for conversations.
        @version 1
        """
        _check_error(
            self._handle,
            self._lib.entropic_storage_open(
                self._handle,
                db_path.encode(),
            ),
        )

    ## @brief Flush and close storage.
    ## @utility
    ## @version 1
    def storage_close(self) -> None:
        """Close the storage backend.

        @brief Flush and close storage.
        @version 1
        """
        _check_error(
            self._handle,
            self._lib.entropic_storage_close(self._handle),
        )

    ## @brief Connect and register an external MCP server at runtime.
    ## @utility
    ## @version 1
    def register_mcp_server(self, name: str, config_json: str) -> None:
        """Register an external MCP server.

        @brief Connect and register an external MCP server at runtime.
        @version 1
        """
        _check_error(
            self._handle,
            self._lib.entropic_register_mcp_server(
                self._handle,
                name.encode(),
                config_json.encode(),
            ),
        )

    ## @brief Disconnect and remove a registered MCP server.
    ## @utility
    ## @version 1
    def deregister_mcp_server(self, name: str) -> None:
        """Deregister an external MCP server.

        @brief Disconnect and remove a registered MCP server.
        @version 1
        """
        _check_error(
            self._handle,
            self._lib.entropic_deregister_mcp_server(
                self._handle,
                name.encode(),
            ),
        )

    ## @brief Get server info JSON from C engine.
    ## @utility
    ## @return Dict of server names to status info.
    ## @version 1
    def list_mcp_servers(self) -> dict[str, Any]:
        """List all MCP servers with status.

        @brief Get server info JSON from C engine.
        @version 1
        """
        result_ptr = self._lib.entropic_list_mcp_servers(self._handle)
        if not result_ptr:
            return {}
        try:
            return json.loads(ctypes.cast(result_ptr, ctypes.c_char_p).value.decode())
        finally:
            self._lib.entropic_free(result_ptr)

    ## @brief Return semver string from C engine.
    ## @utility
    ## @return Version string.
    ## @version 1
    def version(self) -> str:
        """Get the library version string.

        @brief Return semver string from C engine.
        @version 1
        """
        return self._lib.entropic_version().decode()

    ## @brief Return API version for compatibility checks.
    ## @utility
    ## @return Integer API version.
    ## @version 1
    def api_version(self) -> int:
        """Get the C API version integer.

        @brief Return API version for compatibility checks.
        @version 1
        """
        return self._lib.entropic_api_version()

    ## @brief Release all engine resources. Handle becomes invalid.
    ## @utility
    ## @version 1
    def destroy(self) -> None:
        """Destroy the engine handle and free resources.

        @brief Release all engine resources. Handle becomes invalid.
        @version 1
        """
        if self._handle:
            self._lib.entropic_destroy(self._handle)
            self._handle = None

    ## @brief Release handle on garbage collection.
    ## @utility
    ## @version 1
    def __del__(self) -> None:
        """Destructor — ensures handle is freed.

        @brief Release handle on garbage collection.
        @version 1
        """
        self.destroy()

    ## @brief Return self for with-statement usage.
    ## @utility
    ## @return Self.
    ## @version 1
    def __enter__(self) -> EntropicEngine:
        """Context manager entry.

        @brief Return self for with-statement usage.
        @version 1
        """
        return self

    ## @brief Clean up engine on context exit.
    ## @utility
    ## @version 1
    def __exit__(self, *args: object) -> None:
        """Context manager exit — destroys handle.

        @brief Clean up engine on context exit.
        @version 1
        """
        self.destroy()


# ── Result Types ─────────────────────────────────────────


@dataclass
class Message:
    """A conversation message.

    @brief Message with role, content, and optional metadata.
    @version 1
    """

    role: str = ""
    content: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)
    tool_calls: list[dict[str, Any]] = field(default_factory=list)

    ## @brief Construct Message from deserialized JSON.
    ## @utility
    ## @return New Message instance.
    ## @version 1
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Message:
        """Create from JSON dict.

        @brief Construct Message from deserialized JSON.
        @version 1
        """
        return cls(
            role=data.get("role", ""),
            content=data.get("content", ""),
            metadata=data.get("metadata", {}),
            tool_calls=data.get("tool_calls", []),
        )


@dataclass
class ToolCall:
    """A tool call extracted from a generation result.

    @brief Tool invocation with name and arguments.
    @version 1
    """

    name: str = ""
    arguments: dict[str, Any] = field(default_factory=dict)

    ## @brief Construct ToolCall from deserialized JSON.
    ## @utility
    ## @return New ToolCall instance.
    ## @version 1
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> ToolCall:
        """Create from JSON dict.

        @brief Construct ToolCall from deserialized JSON.
        @version 1
        """
        return cls(
            name=data.get("name", ""),
            arguments=data.get("arguments", {}),
        )


@dataclass
class GenerationResult:
    """Result from an entropic_run() call.

    @brief Parsed generation result with response, messages, metrics.
    @version 1
    """

    response: str = ""
    messages: list[Message] = field(default_factory=list)
    tool_calls: list[ToolCall] = field(default_factory=list)
    token_count: int = 0
    generation_time_ms: float = 0.0
    model_name: str = ""
    tier: str = ""
    raw_json: dict[str, Any] = field(default_factory=dict)

    ## @brief Deserialize JSON from entropic_run into GenerationResult.
    ## @utility
    ## @return New GenerationResult instance.
    ## @version 1
    @classmethod
    def from_json(cls, json_str: str) -> GenerationResult:
        """Parse a JSON result string from the C engine.

        @brief Deserialize JSON from entropic_run into GenerationResult.
        @version 1
        """
        data = json.loads(json_str)
        return cls(
            response=data.get("response", ""),
            messages=[Message.from_dict(m) for m in data.get("messages", [])],
            tool_calls=[ToolCall.from_dict(tc) for tc in data.get("tool_calls", [])],
            token_count=data.get("token_count", 0),
            generation_time_ms=data.get("generation_time_ms", 0.0),
            model_name=data.get("model_name", ""),
            tier=data.get("tier", ""),
            raw_json=data,
        )
