# SPDX-License-Identifier: Apache-2.0
# AUTO-GENERATED by scripts/gen_bindings.py — do not edit.
# Run ``inv gen-bindings`` to regenerate; ``inv gen-bindings --check``
# runs in pre-commit and fails if the committed file drifts from the
# header. Source: include/entropic/entropic.h + types/*.h.
"""ctypes bindings for librentropic.so (auto-generated).

This module exposes the entropic C ABI as a flat collection of ctypes
function objects, IntEnum classes, ctypes.Structure types, and CFUNCTYPE
callback typedefs. Symbol names match the C header verbatim.

For symbols not exposed here (none, by construction — the generator
covers every ENTROPIC_EXPORT in entropic.h), load librentropic.so
directly via :func:`entropic._loader.load`.
"""

from __future__ import annotations

import ctypes
import enum

from entropic._loader import load

_lib = load()

# Opaque handle. C side: ``struct entropic_engine*``. From Python it is
# a void* the C functions interpret; pass ``ctypes.byref(handle)`` for
# out-params and ``handle`` for in-params.
entropic_handle_t = ctypes.c_void_p


## @brief Pin restype/argtypes on a ctypes symbol from the loaded .so.
## @utility
## @version 2.2.1
def _bind(name, restype, *argtypes):
    """Pin restype/argtypes on a symbol from the loaded library.

    Helper used by every binding line below.
    """
    fn = getattr(_lib, name)
    fn.restype = restype
    fn.argtypes = list(argtypes)
    return fn


# ── Enums ─────────────────────────────────────

class EntropicError(enum.IntEnum):
    """Mirrors ``entropic_error_t`` from the C header."""

    OK = 0
    INVALID_ARGUMENT = 1
    INVALID_CONFIG = 2
    INVALID_STATE = 3
    MODEL_NOT_FOUND = 4
    LOAD_FAILED = 5
    GENERATE_FAILED = 6
    TOOL_NOT_FOUND = 7
    PERMISSION_DENIED = 8
    PLUGIN_VERSION_MISMATCH = 9
    PLUGIN_LOAD_FAILED = 10
    TIMEOUT = 11
    CANCELLED = 12
    OUT_OF_MEMORY = 13
    IO = 14
    INTERNAL = 15
    SERVER_ALREADY_EXISTS = 16
    SERVER_NOT_FOUND = 17
    CONNECTION_FAILED = 18
    INVALID_HANDLE = 19
    TOOL_EXECUTION_FAILED = 20
    STORAGE_FAILED = 21
    IDENTITY_NOT_FOUND = 22
    ALREADY_RUNNING = 23
    NOT_RUNNING = 24
    NOT_IMPLEMENTED = 25
    INTERRUPTED = 26
    ADAPTER_NOT_FOUND = 27
    ADAPTER_LOAD_FAILED = 28
    ADAPTER_SWAP_FAILED = 29
    ADAPTER_CANCELLED = 30
    GRAMMAR_NOT_FOUND = 31
    GRAMMAR_INVALID = 32
    MCP_KEY_DENIED = 33
    LIMIT_REACHED = 34
    ALREADY_EXISTS = 35
    IN_USE = 36
    PROFILE_NOT_FOUND = 37
    TIME_LIMIT_EXCEEDED = 38
    VALIDATION_FAILED = 39
    COMPACTION_FAILED = 40
    MODEL_NOT_ACTIVE = 41
    EVAL_CONTEXT_FULL = 42
    EVAL_FAILED = 43
    IMAGE_LOAD_FAILED = 44
    IMAGE_TOO_LARGE = 45
    MMPROJ_LOAD_FAILED = 46
    UNSUPPORTED_URL = 47
    NOT_SUPPORTED = 48
    STATE_INCOMPATIBLE = 49
    NO_VISION_TIER = 50
    QUEUE_FULL = 51
    SPECULATIVE_INCOMPATIBLE_ARCH = 52
    TIER_MODEL_TOO_LARGE = 53

class AgentState(enum.IntEnum):
    """Mirrors ``entropic_agent_state_t`` from the C header."""

    IDLE = 0
    PLANNING = 1
    EXECUTING = 2
    WAITING_TOOL = 3
    VERIFYING = 4
    DELEGATING = 5
    COMPLETE = 6
    ERROR = 7
    INTERRUPTED = 8
    PAUSED = 9

class EntropicModelState(enum.IntEnum):
    """Mirrors ``entropic_model_state_t`` from the C header."""

    COLD = 0
    WARM = 1
    ACTIVE = 2

class EntropicDirectiveType(enum.IntEnum):
    """Mirrors ``entropic_directive_type_t`` from the C header."""

    STOP_PROCESSING = 0
    TIER_CHANGE = 1
    DELEGATE = 2
    PIPELINE = 3
    COMPLETE = 4
    CLEAR_SELF_TODOS = 5
    INJECT_CONTEXT = 6
    PRUNE_MESSAGES = 7
    CONTEXT_ANCHOR = 8
    PHASE_CHANGE = 9
    NOTIFY_PRESENTER = 10

class EntropicComputeBackend(enum.IntEnum):
    """Mirrors ``entropic_compute_backend_t`` from the C header."""

    CPU = 0
    CUDA = 1
    VULKAN = 2

class EntropicHookPoint(enum.IntEnum):
    """Mirrors ``entropic_hook_point_t`` from the C header."""

    PRE_GENERATE = 0
    POST_GENERATE = 1
    ON_STREAM_TOKEN = 2
    PRE_TOOL_CALL = 3
    POST_TOOL_CALL = 4
    ON_LOOP_ITERATION = 5
    ON_STATE_CHANGE = 6
    ON_ERROR = 7
    ON_DELEGATE = 8
    ON_DELEGATE_COMPLETE = 9
    ON_CONTEXT_ASSEMBLE = 10
    ON_PRE_COMPACT = 11
    ON_POST_COMPACT = 12
    ON_MODEL_LOAD = 13
    ON_MODEL_UNLOAD = 14
    ON_PERMISSION_CHECK = 15
    ON_ADAPTER_SWAP = 16
    ON_VRAM_PRESSURE = 17
    ON_DIRECTIVE = 18
    ON_CUSTOM_DIRECTIVE = 19
    ON_LOOP_START = 20
    ON_LOOP_END = 21
    ON_COMPLETE = 22

class EntDecision(enum.IntEnum):
    """Mirrors ``ent_decision_t`` from the C header."""

    ACCEPT = 0
    REJECT = 1

class EntropicMcpAccessLevel(enum.IntEnum):
    """Mirrors ``entropic_mcp_access_level_t`` from the C header."""

    NONE = 0
    READ = 1
    WRITE = 2

# ── Structs ───────────────────────────────────

class EntDelegationRequest(ctypes.Structure):
    """Mirrors ``ent_delegation_request_t`` from the C header."""

    _fields_ = [
        ("delegation_id", ctypes.c_char_p),
        ("target_tier", ctypes.c_char_p),
        ("task", ctypes.c_char_p),
        ("depth", ctypes.c_int),
        ("is_pipeline", ctypes.c_int),
    ]

class EntDelegationResult(ctypes.Structure):
    """Mirrors ``ent_delegation_result_t`` from the C header."""

    _fields_ = [
        ("delegation_id", ctypes.c_char_p),
        ("target_tier", ctypes.c_char_p),
        ("success", ctypes.c_int),
        ("summary", ctypes.c_char_p),
        ("patch", ctypes.c_char_p),
        ("patch_len", ctypes.c_size_t),
        ("files_touched", ctypes.POINTER(ctypes.c_char_p)),
        ("files_touched_len", ctypes.c_size_t),
    ]

class EntropicLogprobResult(ctypes.Structure):
    """Mirrors ``entropic_logprob_result_t`` from the C header."""

    _fields_ = [
        ("logprobs", ctypes.POINTER(ctypes.c_float)),
        ("tokens", ctypes.POINTER(ctypes.c_int32)),
        ("perplexity", ctypes.c_float),
        ("total_logprob", ctypes.c_float),
        ("n_tokens", ctypes.c_int),
        ("n_logprobs", ctypes.c_int),
    ]

# ── Callback typedefs (named) ─────────────────

HOOK_CB = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_int, ctypes.c_char_p, ctypes.POINTER(ctypes.c_char_p), ctypes.c_void_p)
RESIDENCY_OBSERVER_CB = ctypes.CFUNCTYPE(None, ctypes.c_int, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_size_t, ctypes.c_void_p)
DELEGATION_START_CB = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.POINTER(EntDelegationRequest), ctypes.c_void_p)
DELEGATION_COMPLETE_CB = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.POINTER(EntDelegationResult), ctypes.c_void_p)
ATTEMPT_BOUNDARY_CB = ctypes.CFUNCTYPE(None, ctypes.c_int, ctypes.c_void_p)
COMPACTOR_CB = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_char_p, ctypes.c_char_p, ctypes.POINTER(ctypes.c_char_p), ctypes.POINTER(ctypes.c_char_p), ctypes.c_void_p)

# ── Callback typedefs (from inline params) ────

TOKEN_CB = ctypes.CFUNCTYPE(None, ctypes.c_char_p, ctypes.c_size_t, ctypes.c_void_p)
STREAM_OBSERVER_CB = ctypes.CFUNCTYPE(None, ctypes.c_char_p, ctypes.c_size_t, ctypes.c_void_p)
STATE_OBSERVER_CB = ctypes.CFUNCTYPE(None, ctypes.c_int, ctypes.c_void_p)
CRITIQUE_START_CB = ctypes.CFUNCTYPE(None, ctypes.c_void_p)
CRITIQUE_END_CB = ctypes.CFUNCTYPE(None, ctypes.c_void_p)
QUEUE_OBSERVER_CB = ctypes.CFUNCTYPE(None, ctypes.c_char_p, ctypes.c_size_t, ctypes.c_void_p)

# gh#22 backward-compat aliases for the CFUNCTYPE typedefs.
HOOK_CALLBACK_CB = HOOK_CB
TOKEN_STREAM_CB = TOKEN_CB

# ── Bindings ──────────────────────────────────

entropic_create = _bind("entropic_create", ctypes.c_int, ctypes.POINTER(entropic_handle_t))
entropic_configure = _bind("entropic_configure", ctypes.c_int, entropic_handle_t, ctypes.c_char_p)
entropic_configure_from_file = _bind("entropic_configure_from_file", ctypes.c_int, entropic_handle_t, ctypes.c_char_p)
entropic_configure_dir = _bind("entropic_configure_dir", ctypes.c_int, entropic_handle_t, ctypes.c_char_p)
entropic_destroy = _bind("entropic_destroy", None, entropic_handle_t)
entropic_version = _bind("entropic_version", ctypes.c_char_p)
entropic_api_version = _bind("entropic_api_version", ctypes.c_int)
entropic_seconds_since_last_activity = _bind("entropic_seconds_since_last_activity", ctypes.c_int64, entropic_handle_t)
entropic_alloc = _bind("entropic_alloc", ctypes.c_void_p, ctypes.c_size_t)
entropic_free = _bind("entropic_free", None, ctypes.c_void_p)
entropic_run = _bind("entropic_run", ctypes.c_int, entropic_handle_t, ctypes.c_char_p, ctypes.POINTER(ctypes.c_char_p))
entropic_run_streaming = _bind("entropic_run_streaming", ctypes.c_int, entropic_handle_t, ctypes.c_char_p, TOKEN_CB, ctypes.c_void_p, ctypes.POINTER(ctypes.c_int))
entropic_run_messages = _bind("entropic_run_messages", ctypes.c_int, entropic_handle_t, ctypes.c_char_p, ctypes.POINTER(ctypes.c_char_p))
entropic_run_messages_streaming = _bind("entropic_run_messages_streaming", ctypes.c_int, entropic_handle_t, ctypes.c_char_p, TOKEN_CB, ctypes.c_void_p, ctypes.POINTER(ctypes.c_int))
entropic_set_stream_observer = _bind("entropic_set_stream_observer", ctypes.c_int, entropic_handle_t, STREAM_OBSERVER_CB, ctypes.c_void_p)
entropic_set_state_observer = _bind("entropic_set_state_observer", ctypes.c_int, entropic_handle_t, STATE_OBSERVER_CB, ctypes.c_void_p)
entropic_set_critique_callbacks = _bind("entropic_set_critique_callbacks", ctypes.c_int, entropic_handle_t, CRITIQUE_START_CB, CRITIQUE_END_CB, ctypes.c_void_p)
entropic_interrupt = _bind("entropic_interrupt", ctypes.c_int, entropic_handle_t)
entropic_queue_user_message = _bind("entropic_queue_user_message", ctypes.c_int, entropic_handle_t, ctypes.c_char_p)
entropic_user_message_queue_depth = _bind("entropic_user_message_queue_depth", ctypes.c_int, entropic_handle_t, ctypes.POINTER(ctypes.c_size_t))
entropic_clear_user_message_queue = _bind("entropic_clear_user_message_queue", ctypes.c_int, entropic_handle_t)
entropic_set_queue_observer = _bind("entropic_set_queue_observer", ctypes.c_int, entropic_handle_t, QUEUE_OBSERVER_CB, ctypes.c_void_p)
entropic_speculative_compat = _bind("entropic_speculative_compat", ctypes.c_int, entropic_handle_t, ctypes.POINTER(ctypes.c_int), ctypes.POINTER(ctypes.c_char_p))
entropic_set_residency_observer = _bind("entropic_set_residency_observer", ctypes.c_int, entropic_handle_t, RESIDENCY_OBSERVER_CB, ctypes.c_void_p)
entropic_residency_snapshot = _bind("entropic_residency_snapshot", ctypes.c_int, entropic_handle_t, ctypes.POINTER(ctypes.c_char_p))
entropic_context_clear = _bind("entropic_context_clear", ctypes.c_int, entropic_handle_t)
entropic_context_get = _bind("entropic_context_get", ctypes.c_int, entropic_handle_t, ctypes.POINTER(ctypes.c_char_p))
entropic_context_count = _bind("entropic_context_count", ctypes.c_int, entropic_handle_t, ctypes.POINTER(ctypes.c_size_t))
entropic_context_usage = _bind("entropic_context_usage", ctypes.c_int, entropic_handle_t, ctypes.POINTER(ctypes.c_size_t), ctypes.POINTER(ctypes.c_size_t))
entropic_metrics_json = _bind("entropic_metrics_json", ctypes.c_int, entropic_handle_t, ctypes.POINTER(ctypes.c_char_p))
entropic_set_delegation_callbacks = _bind("entropic_set_delegation_callbacks", ctypes.c_int, entropic_handle_t, DELEGATION_START_CB, DELEGATION_COMPLETE_CB, ctypes.c_void_p)
entropic_validation_set_auto_retry = _bind("entropic_validation_set_auto_retry", ctypes.c_int, entropic_handle_t, ctypes.c_int)
entropic_validation_resume_retry = _bind("entropic_validation_resume_retry", ctypes.c_int, entropic_handle_t)
entropic_validation_accept_last = _bind("entropic_validation_accept_last", ctypes.c_int, entropic_handle_t)
entropic_set_attempt_boundary_cb = _bind("entropic_set_attempt_boundary_cb", ctypes.c_int, entropic_handle_t, ATTEMPT_BOUNDARY_CB, ctypes.c_void_p)
entropic_register_mcp_server = _bind("entropic_register_mcp_server", ctypes.c_int, entropic_handle_t, ctypes.c_char_p, ctypes.c_char_p)
entropic_deregister_mcp_server = _bind("entropic_deregister_mcp_server", ctypes.c_int, entropic_handle_t, ctypes.c_char_p)
entropic_list_mcp_servers = _bind("entropic_list_mcp_servers", ctypes.c_char_p, entropic_handle_t)
entropic_storage_open = _bind("entropic_storage_open", ctypes.c_int, entropic_handle_t, ctypes.c_char_p)
entropic_storage_close = _bind("entropic_storage_close", ctypes.c_int, entropic_handle_t)
entropic_load_identity = _bind("entropic_load_identity", ctypes.c_int, entropic_handle_t, ctypes.c_char_p)
entropic_get_identity = _bind("entropic_get_identity", ctypes.c_int, entropic_handle_t, ctypes.POINTER(ctypes.c_char_p))
entropic_register_hook = _bind("entropic_register_hook", ctypes.c_int, entropic_handle_t, ctypes.c_int, HOOK_CB, ctypes.c_void_p, ctypes.c_int)
entropic_deregister_hook = _bind("entropic_deregister_hook", ctypes.c_int, entropic_handle_t, ctypes.c_int, HOOK_CB, ctypes.c_void_p)
entropic_adapter_load = _bind("entropic_adapter_load", ctypes.c_int, entropic_handle_t, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_float)
entropic_adapter_unload = _bind("entropic_adapter_unload", ctypes.c_int, entropic_handle_t, ctypes.c_char_p)
entropic_adapter_swap = _bind("entropic_adapter_swap", ctypes.c_int, entropic_handle_t, ctypes.c_char_p)
entropic_adapter_state = _bind("entropic_adapter_state", ctypes.c_int, entropic_handle_t, ctypes.c_char_p)
entropic_adapter_info = _bind("entropic_adapter_info", ctypes.c_char_p, entropic_handle_t, ctypes.c_char_p)
entropic_adapter_list = _bind("entropic_adapter_list", ctypes.c_char_p, entropic_handle_t)
entropic_grammar_register = _bind("entropic_grammar_register", ctypes.c_int, entropic_handle_t, ctypes.c_char_p, ctypes.c_char_p)
entropic_grammar_register_file = _bind("entropic_grammar_register_file", ctypes.c_int, entropic_handle_t, ctypes.c_char_p, ctypes.c_char_p)
entropic_grammar_deregister = _bind("entropic_grammar_deregister", ctypes.c_int, entropic_handle_t, ctypes.c_char_p)
entropic_grammar_get = _bind("entropic_grammar_get", ctypes.c_char_p, entropic_handle_t, ctypes.c_char_p)
entropic_grammar_validate = _bind("entropic_grammar_validate", ctypes.c_char_p, ctypes.c_char_p)
entropic_grammar_list = _bind("entropic_grammar_list", ctypes.c_char_p, entropic_handle_t)
entropic_profile_register = _bind("entropic_profile_register", ctypes.c_int, entropic_handle_t, ctypes.c_char_p)
entropic_profile_deregister = _bind("entropic_profile_deregister", ctypes.c_int, entropic_handle_t, ctypes.c_char_p)
entropic_profile_get = _bind("entropic_profile_get", ctypes.c_char_p, entropic_handle_t, ctypes.c_char_p)
entropic_profile_list = _bind("entropic_profile_list", ctypes.c_char_p, entropic_handle_t)
entropic_throughput_tok_per_sec = _bind("entropic_throughput_tok_per_sec", ctypes.c_double, entropic_handle_t, ctypes.c_char_p)
entropic_throughput_reset = _bind("entropic_throughput_reset", None, entropic_handle_t, ctypes.c_char_p)
entropic_grant_mcp_key = _bind("entropic_grant_mcp_key", ctypes.c_int, entropic_handle_t, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_int)
entropic_revoke_mcp_key = _bind("entropic_revoke_mcp_key", ctypes.c_int, entropic_handle_t, ctypes.c_char_p, ctypes.c_char_p)
entropic_check_mcp_key = _bind("entropic_check_mcp_key", ctypes.c_int, entropic_handle_t, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_int)
entropic_list_mcp_keys = _bind("entropic_list_mcp_keys", ctypes.c_char_p, entropic_handle_t, ctypes.c_char_p)
entropic_grant_mcp_key_from = _bind("entropic_grant_mcp_key_from", ctypes.c_int, entropic_handle_t, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_int)
entropic_serialize_mcp_keys = _bind("entropic_serialize_mcp_keys", ctypes.c_char_p, entropic_handle_t)
entropic_deserialize_mcp_keys = _bind("entropic_deserialize_mcp_keys", ctypes.c_int, entropic_handle_t, ctypes.c_char_p)
entropic_audit_flush = _bind("entropic_audit_flush", ctypes.c_int, entropic_handle_t)
entropic_audit_count = _bind("entropic_audit_count", ctypes.c_int, entropic_handle_t, ctypes.POINTER(ctypes.c_size_t))
entropic_audit_read = _bind("entropic_audit_read", ctypes.c_int, entropic_handle_t, ctypes.c_char_p, ctypes.c_char_p, ctypes.POINTER(ctypes.c_char_p))
entropic_create_identity = _bind("entropic_create_identity", ctypes.c_int, entropic_handle_t, ctypes.c_char_p)
entropic_update_identity = _bind("entropic_update_identity", ctypes.c_int, entropic_handle_t, ctypes.c_char_p, ctypes.c_char_p)
entropic_destroy_identity = _bind("entropic_destroy_identity", ctypes.c_int, entropic_handle_t, ctypes.c_char_p)
entropic_get_identity_config = _bind("entropic_get_identity_config", ctypes.c_char_p, entropic_handle_t, ctypes.c_char_p)
entropic_list_identities = _bind("entropic_list_identities", ctypes.c_char_p, entropic_handle_t)
entropic_identity_count = _bind("entropic_identity_count", ctypes.c_int, entropic_handle_t, ctypes.POINTER(ctypes.c_size_t), ctypes.POINTER(ctypes.c_size_t))
entropic_compact = _bind("entropic_compact", ctypes.c_int, entropic_handle_t, ctypes.c_char_p, ctypes.POINTER(ctypes.c_char_p))
entropic_register_compactor = _bind("entropic_register_compactor", ctypes.c_int, entropic_handle_t, ctypes.c_char_p, COMPACTOR_CB, ctypes.c_void_p)
entropic_deregister_compactor = _bind("entropic_deregister_compactor", ctypes.c_int, entropic_handle_t, ctypes.c_char_p)
entropic_get_default_compactor = _bind("entropic_get_default_compactor", ctypes.c_int, entropic_handle_t, ctypes.POINTER(COMPACTOR_CB), ctypes.POINTER(ctypes.c_void_p))
entropic_get_logprobs = _bind("entropic_get_logprobs", ctypes.c_int, entropic_handle_t, ctypes.c_char_p, ctypes.POINTER(ctypes.c_int32), ctypes.c_int, ctypes.POINTER(EntropicLogprobResult))
entropic_compute_perplexity = _bind("entropic_compute_perplexity", ctypes.c_int, entropic_handle_t, ctypes.c_char_p, ctypes.POINTER(ctypes.c_int32), ctypes.c_int, ctypes.POINTER(ctypes.c_float))
entropic_free_logprob_result = _bind("entropic_free_logprob_result", None, ctypes.POINTER(EntropicLogprobResult))
entropic_validation_set_enabled = _bind("entropic_validation_set_enabled", ctypes.c_int, entropic_handle_t, ctypes.c_bool)
entropic_validation_set_identity = _bind("entropic_validation_set_identity", ctypes.c_int, entropic_handle_t, ctypes.c_char_p, ctypes.c_bool)
entropic_validation_last_result = _bind("entropic_validation_last_result", ctypes.c_char_p, entropic_handle_t)
entropic_model_has_vision = _bind("entropic_model_has_vision", ctypes.c_int, entropic_handle_t, ctypes.c_char_p)
entropic_get_diagnostic_prompt = _bind("entropic_get_diagnostic_prompt", ctypes.c_int, entropic_handle_t, ctypes.POINTER(ctypes.c_char_p))
