@startuml
skinparam backgroundColor #FEFEFE
skinparam noteBorderColor #999999
skinparam noteBackgroundColor #FFFFEE
title test_generation_error_captured\n<size:11>[PASSED] 0.0s</size>

participant "Test" as T
participant "Application" as App

T -> App: (internal test)
App --> T: PASSED
note right #palegreen: 0.0s

@enduml